name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.13.1
        with:
          minikube version: 'v1.26.0'
          kubernetes version: 'v1.32.0'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for Minikube
        run: |
          echo "Esperando que Minikube esté listo..."
          kubectl wait --for=condition=Ready nodes --timeout=60s

      - name: Deploy app to Minikube
        run: |
          kubectl create deployment my-app --image=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
          kubectl expose deployment my-app --type=NodePort --port=3000
          kubectl get all
